# Version 8.0.100
name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.100' 

      - name: Cache NuGet packages
        uses: actions/cache@v2
        with:
          path: |
            **/*.nuget
            **/packages/*
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        if: runner.os != 'Windows'

      - name: Restore dependencies
        run: dotnet restore

      - name: Clean
        run: dotnet clean

      - name: Set Platform
        run: echo "::set-env name=DOTNET_CLI_TELEMETRY_OPTOUT::1" #Apprently this helps according to StackOverflow...
        shell: bash

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release